services:
  hosts:
    auth: http://localhost:8089
    media: http://localhost:8184
    reaction: http://localhost:8185
    gateway: http://localhost:7777
    follow: http://localhost:8182
    thread: http://localhost:8183
  ports:
    auth: 8089
    media: 8184
    gateway: 7777
    follow: 8182
    thread: 8183
    reaction: 8185

spring:
  security:
    oauth2:
      resourceserver:
        user-info-uri: ${services.hosts.auth}/internal/user-info
        jwt:
          issuer-uri: http://localhost:8089