server:
  port: ${services.ports.auth}
spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8089
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth
      auto-index-creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thread_db
    username: postgres
    password: 1
    hikari:
      schema: auth
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: auth
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
  sql:
    init:
      mode: never
