server:
  port: ${services.ports.follow}
spring:
  application:
    name: follow

  datasource:
    url: jdbc:postgresql://localhost:5432/thread_db
    username: postgres
    password: 1

  jpa:
    properties:
      hibernate:
        default_schema: follow

    hibernate:
      ddl-auto: update

    show-sql: true