server:
  port: ${services.ports.gateway}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      restricted-paths:
        - /api/v1/[a-zA-Z]+/internal/.*
      global-filter:
        - LoggingGlobalFilter
        - RestrictedPathFilter
      routes:
        - id: follow-route
          uri: ${services.hosts.follow}
          predicates:
            - Path=/api/v1/follow/**
          filters:
            - RewritePath=/api/v1/follow/(?<remaining>.*), /${remaining}
        - id: thread-route
          uri: ${services.hosts.thread}
          predicates:
            - Path=/api/v1/thread/**
          filters:
            - RewritePath=/api/v1/thread/(?<remaining>.*), /${remaining}
        - id: media-route
          uri: ${services.hosts.media}
          predicates:
            - Path=/api/v1/media/**
          filters:
            - RewritePath=/api/v1/media/(?<remaining>.*), /${remaining}
        - id: reaction-route
          uri: ${services.hosts.reaction}
          predicates:
            - Path=/api/v1/reaction/**
          filters:
            - RewritePath=/api/v1/reaction/(?<remaining>.*), /${remaining}
        - id: auth-route
          uri: ${services.hosts.auth}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<remaining>.*),/${remaining}
