server:
  port: ${services.ports.gateway}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      restricted-paths:
        - /api/v1/[a-zA-Z]+/internal/.*
      global-filter:
        - LoggingGlobalFilter
        - RestrictedPathFilter
      routes:
        - id: user-route
          uri: ${services.hosts.user}
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/api/v1/user/(?<remaining>.*), /api/v1/user/${remaining}
        - id: thread-route
          uri: ${services.hosts.thread}
          predicates:
            - Path=/api/v1/thread/**
          filters:
            - RewritePath=/api/v1/thread/(?<remaining>.*), /api/v1/thread/${remaining}
        - id: media-route
          uri: ${services.hosts.media}
          predicates:
            - Path=/api/v1/media/**
          filters:
            - RewritePath=/api/v1/media/(?<remaining>.*), /api/v1/media/${remaining}
        - id: reaction-route
          uri: ${services.hosts.reaction}
          predicates:
            - Path=/api/v1/reaction/**
          filters:
            - RewritePath=/api/v1/reaction/(?<remaining>.*), /api/v1/reaction/${remaining}
