server:
  port: ${services.ports.reaction}
spring:
  application:
    name: reaction

  datasource:
    url: jdbc:postgresql://localhost:5432/thread_db
    username: postgres
    password: 1

  jpa:
    properties:
      hibernate:
        default_schema: reaction

    hibernate:
      ddl-auto: update

    show-sql: true